# Application Configuration
spring.application.name=HeroModule
server.port=15479

# HTTPS Configuration
server.ssl.key-store-type=JKS
server.ssl.key-store=classpath:ssl/hero-service-keystore.jks
server.ssl.key-store-password=changeit
server.ssl.trust-store-type=JKS
server.ssl.trust-store=classpath:ssl/hero-service-truststore.jks
server.ssl.trust-store-password=changeit
server.ssl.key-alias=hero-service
server.ssl.enabled=true

# Redirect HTTP to HTTPS
server.http.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:s367452}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:CSui7vGaIue5t9n6}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# External Service Configuration
humanbeing.service.url=https://localhost:15478/api/v1

# CORS Configuration
cors.allowed-origins=https://localhost:5173,https://se.ifmo.ru