spring:
  application:
    name: hero-service

server:
  port: ${PORT:0}

eureka:
  instance:
    prefer-ip-address: true
    secure-port-enabled: true
    non-secure-port-enabled: false

    secure-port: ${local.server.port}

    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${local.server.port}